# Generated by Django 5.0.1 on 2024-01-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Movie',
        ),
    ]
